apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    app: demo-voting-app
spec:
  #type: LoadBalancer : Note: LoadBalancer will only work on cloud platforms, so we are using NodePort instead of LoadBalancer
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: voting-app-pod
    app: demo-voting-app